version: '3.1'

services:
    frontend:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        container_name: frontend
        networks:
            - net
        environment: 
            NODE_ENV: "production"
        ports:
            - 8080:80
    backend:
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        container_name: backend
        networks:
            - net
    image-service:
        build:
            context: ./image-service/
            dockerfile: Dockerfile
        container_name: image-service
        networks:
            - net

networks:
    net:
