{
 "title": "Metrics Compose",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"backend|frontend|image-service|database\"} / (1024 * 1024)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "The CPU usage in the last 5 minutes (split up by core)",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"backend|frontend|image-service|database\"}[5m])",
     "legendFormat": "{{name}} [{{cpu}}]"
    }
   ]
  },
  {
   "title": "Bytes receive rate",
   "type": "graph",
   "description": "Bytes received over the network by the container per second in the last 10 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{interface=\"eth0\", name=~\"backend|frontend|image-service|database\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes transmit rate",
   "type": "graph",
   "description": "Bytes transmitted over the network by the container per second in the last 15 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\"backend|frontend|image-service|database\", interface=\"eth0\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}